import 'package:flutter/material.dart';

/// Gestore delle traduzioni dell'app
class LocalizationManager extends ChangeNotifier {
  static final LocalizationManager _instance = LocalizationManager._internal();
  factory LocalizationManager() => _instance;
  LocalizationManager._internal();

  Locale _currentLocale = const Locale('it', 'IT');
  Locale get currentLocale => _currentLocale;

  // Traduzioni
  final Map<String, Map<String, String>> _translations = {
    'it': {
      // Impostazioni
      'settings': 'Impostazioni',
      'appearance': 'Aspetto',
      'dark_mode': 'Modalità scura',
      'dark_mode_active': 'Attiva',
      'dark_mode_inactive': 'Disattiva',
      'notifications': 'Notifiche',
      'push_notifications': 'Notifiche push',
      'push_notifications_subtitle': 'Ricevi notifiche sull\'app',
      'push_notifications_detail': 'Notifiche immediate',
      'privacy_security': 'Privacy e Sicurezza',
      'privacy': 'Privacy',
      'privacy_subtitle': 'Gestisci la tua privacy',
      'terms_conditions': 'Termini e condizioni',
      'terms_conditions_subtitle': 'Leggi i termini di utilizzo',
      'privacy_policy': 'Informativa sulla privacy',
      'privacy_policy_subtitle': 'Come utilizziamo i tuoi dati',
      'support': 'Supporto',
      'help_support': 'Aiuto e supporto',
      'help_support_subtitle': 'Domande frequenti e assistenza',
      'info': 'Informazioni',
      'info_subtitle': 'Versione 1.0.0',
      'general': 'Generale',
      'language': 'Lingua',
      'language_subtitle': 'Italiano',
      'apply': 'Applica',
      'select_language': 'Seleziona la lingua',
      'select_language_subtitle': 'Scegli la lingua che preferisci per l\'app.',
      'language_change_info': 'La modifica della lingua richiederà il riavvio dell\'app per essere applicata completamente.',
      // Home
      'home': 'Home',
      'map': 'Mappa',
      'search': 'Cerca',
      'available_cells': 'Disponibilità',
      'cells': 'celle',
      'open': 'Apri',
      // Profile
      'profile': 'Profilo',
      'usage_history': 'Storico utilizzi',
      'active_cells': 'Celle attive',
      'borrowed_items': 'Oggetti in prestito',
      'active_deposits': 'Depositi attivi',
      'pickup_orders': 'Ordini da ritirare',
      'return': 'Restituisci',
      'unlock_cell': 'Sblocca cella',
      'reports': 'Segnalazioni',
      'new_report': 'Nuova segnalazione',
      'donate': 'Donare un oggetto',
      'new_donation': 'Nuova donazione',
      'help': 'Aiuto e supporto',
      'logout': 'Esci',
      // Reports
      'report_issue': 'Segnala un problema',
      'category': 'Categoria',
      'description': 'Descrizione',
      'photo': 'Foto',
      'send_report': 'Invia segnalazione',
      'report_sent': 'Segnalazione inviata',
      'report_sent_message': 'La tua segnalazione è stata inviata con successo.',
      // Donations
      'donation_history': 'Storico donazioni',
      'donation_status_pending': 'In attesa di verifica',
      'donation_status_confirmed': 'Confermata',
      'donation_status_delivered': 'Consegnata',
      'donation_status_rejected': 'Rifiutata',
      // Common
      'cancel': 'Annulla',
      'confirm': 'Conferma',
      'ok': 'OK',
      'back': 'Indietro',
      'close': 'Chiudi',
      'save': 'Salva',
      'delete': 'Cancella',
      'edit': 'Modifica',
      'completed': 'Completato',
      'report_problem': 'Segnala un problema',
    },
    'en': {
      'settings': 'Settings',
      'appearance': 'Appearance',
      'dark_mode': 'Dark mode',
      'dark_mode_active': 'Active',
      'dark_mode_inactive': 'Inactive',
      'notifications': 'Notifications',
      'push_notifications': 'Push notifications',
      'push_notifications_subtitle': 'Receive notifications on the app',
      'push_notifications_detail': 'Immediate notifications',
      'privacy_security': 'Privacy & Security',
      'privacy': 'Privacy',
      'privacy_subtitle': 'Manage your privacy',
      'terms_conditions': 'Terms and Conditions',
      'terms_conditions_subtitle': 'Read the terms of use',
      'privacy_policy': 'Privacy Policy',
      'privacy_policy_subtitle': 'How we use your data',
      'support': 'Support',
      'help_support': 'Help & Support',
      'help_support_subtitle': 'Frequently asked questions and assistance',
      'info': 'Information',
      'info_subtitle': 'Version 1.0.0',
      'general': 'General',
      'language': 'Language',
      'language_subtitle': 'English',
      'apply': 'Apply',
      'select_language': 'Select language',
      'select_language_subtitle': 'Choose your preferred language for the app.',
      'language_change_info': 'Changing the language will require restarting the app to be fully applied.',
      'home': 'Home',
      'map': 'Map',
      'search': 'Search',
      'available_cells': 'Availability',
      'cells': 'cells',
      'open': 'Open',
      'profile': 'Profile',
      'usage_history': 'Usage History',
      'active_cells': 'Active Cells',
      'borrowed_items': 'Borrowed Items',
      'active_deposits': 'Active Deposits',
      'pickup_orders': 'Pickup Orders',
      'return': 'Return',
      'unlock_cell': 'Unlock Cell',
      'reports': 'Reports',
      'new_report': 'New Report',
      'donate': 'Donate an Item',
      'new_donation': 'New Donation',
      'help': 'Help & Support',
      'logout': 'Logout',
      'report_issue': 'Report an Issue',
      'category': 'Category',
      'description': 'Description',
      'photo': 'Photo',
      'send_report': 'Send Report',
      'report_sent': 'Report Sent',
      'report_sent_message': 'Your report has been sent successfully.',
      'donation_history': 'Donation History',
      'donation_status_pending': 'Pending Verification',
      'donation_status_confirmed': 'Confirmed',
      'donation_status_delivered': 'Delivered',
      'donation_status_rejected': 'Rejected',
      'cancel': 'Cancel',
      'confirm': 'Confirm',
      'ok': 'OK',
      'back': 'Back',
      'close': 'Close',
      'save': 'Save',
      'delete': 'Delete',
      'edit': 'Edit',
      'completed': 'Completed',
      'report_problem': 'Report a Problem',
    },
    'de': {
      'settings': 'Einstellungen',
      'appearance': 'Aussehen',
      'dark_mode': 'Dunkler Modus',
      'dark_mode_active': 'Aktiv',
      'dark_mode_inactive': 'Inaktiv',
      'notifications': 'Benachrichtigungen',
      'push_notifications': 'Push-Benachrichtigungen',
      'push_notifications_subtitle': 'Erhalten Sie Benachrichtigungen in der App',
      'push_notifications_detail': 'Sofortige Benachrichtigungen',
      'privacy_security': 'Datenschutz & Sicherheit',
      'privacy': 'Datenschutz',
      'privacy_subtitle': 'Verwalten Sie Ihre Privatsphäre',
      'terms_conditions': 'Allgemeine Geschäftsbedingungen',
      'terms_conditions_subtitle': 'Lesen Sie die Nutzungsbedingungen',
      'privacy_policy': 'Datenschutzerklärung',
      'privacy_policy_subtitle': 'Wie wir Ihre Daten verwenden',
      'support': 'Support',
      'help_support': 'Hilfe & Support',
      'help_support_subtitle': 'Häufig gestellte Fragen und Unterstützung',
      'info': 'Informationen',
      'info_subtitle': 'Version 1.0.0',
      'general': 'Allgemein',
      'language': 'Sprache',
      'language_subtitle': 'Deutsch',
      'apply': 'Anwenden',
      'select_language': 'Sprache auswählen',
      'select_language_subtitle': 'Wählen Sie Ihre bevorzugte Sprache für die App.',
      'language_change_info': 'Die Änderung der Sprache erfordert einen Neustart der App, um vollständig angewendet zu werden.',
      'home': 'Startseite',
      'map': 'Karte',
      'search': 'Suchen',
      'available_cells': 'Verfügbarkeit',
      'cells': 'Zellen',
      'open': 'Öffnen',
      'profile': 'Profil',
      'usage_history': 'Nutzungsverlauf',
      'active_cells': 'Aktive Zellen',
      'borrowed_items': 'Ausgeliehene Artikel',
      'active_deposits': 'Aktive Einzahlungen',
      'pickup_orders': 'Abholbestellungen',
      'return': 'Zurückgeben',
      'unlock_cell': 'Zelle entsperren',
      'reports': 'Meldungen',
      'new_report': 'Neue Meldung',
      'donate': 'Artikel spenden',
      'new_donation': 'Neue Spende',
      'help': 'Hilfe & Support',
      'logout': 'Abmelden',
      'report_issue': 'Problem melden',
      'category': 'Kategorie',
      'description': 'Beschreibung',
      'photo': 'Foto',
      'send_report': 'Meldung senden',
      'report_sent': 'Meldung gesendet',
      'report_sent_message': 'Ihre Meldung wurde erfolgreich gesendet.',
      'donation_history': 'Spendenverlauf',
      'donation_status_pending': 'Ausstehende Überprüfung',
      'donation_status_confirmed': 'Bestätigt',
      'donation_status_delivered': 'Geliefert',
      'donation_status_rejected': 'Abgelehnt',
      'cancel': 'Abbrechen',
      'confirm': 'Bestätigen',
      'ok': 'OK',
      'back': 'Zurück',
      'close': 'Schließen',
      'save': 'Speichern',
      'delete': 'Löschen',
      'edit': 'Bearbeiten',
      'completed': 'Abgeschlossen',
      'report_problem': 'Problem melden',
    },
    'fr': {
      'settings': 'Paramètres',
      'appearance': 'Apparence',
      'dark_mode': 'Mode sombre',
      'dark_mode_active': 'Actif',
      'dark_mode_inactive': 'Inactif',
      'notifications': 'Notifications',
      'push_notifications': 'Notifications push',
      'push_notifications_subtitle': 'Recevoir des notifications sur l\'app',
      'push_notifications_detail': 'Notifications immédiates',
      'privacy_security': 'Confidentialité et Sécurité',
      'privacy': 'Confidentialité',
      'privacy_subtitle': 'Gérer votre confidentialité',
      'terms_conditions': 'Termes et Conditions',
      'terms_conditions_subtitle': 'Lire les conditions d\'utilisation',
      'privacy_policy': 'Politique de Confidentialité',
      'privacy_policy_subtitle': 'Comment nous utilisons vos données',
      'support': 'Support',
      'help_support': 'Aide et Support',
      'help_support_subtitle': 'Questions fréquentes et assistance',
      'info': 'Informations',
      'info_subtitle': 'Version 1.0.0',
      'general': 'Général',
      'language': 'Langue',
      'language_subtitle': 'Français',
      'apply': 'Appliquer',
      'select_language': 'Sélectionner la langue',
      'select_language_subtitle': 'Choisissez votre langue préférée pour l\'app.',
      'language_change_info': 'Le changement de langue nécessitera le redémarrage de l\'app pour être complètement appliqué.',
      'home': 'Accueil',
      'map': 'Carte',
      'search': 'Rechercher',
      'available_cells': 'Disponibilité',
      'cells': 'cellules',
      'open': 'Ouvrir',
      'profile': 'Profil',
      'usage_history': 'Historique d\'utilisation',
      'active_cells': 'Cellules actives',
      'borrowed_items': 'Articles empruntés',
      'active_deposits': 'Dépôts actifs',
      'pickup_orders': 'Commandes à récupérer',
      'return': 'Retourner',
      'unlock_cell': 'Déverrouiller la cellule',
      'reports': 'Signalements',
      'new_report': 'Nouveau signalement',
      'donate': 'Faire un don',
      'new_donation': 'Nouveau don',
      'help': 'Aide et Support',
      'logout': 'Déconnexion',
      'report_issue': 'Signaler un problème',
      'category': 'Catégorie',
      'description': 'Description',
      'photo': 'Photo',
      'send_report': 'Envoyer le signalement',
      'report_sent': 'Signalement envoyé',
      'report_sent_message': 'Votre signalement a été envoyé avec succès.',
      'donation_history': 'Historique des dons',
      'donation_status_pending': 'En attente de vérification',
      'donation_status_confirmed': 'Confirmé',
      'donation_status_delivered': 'Livré',
      'donation_status_rejected': 'Rejeté',
      'cancel': 'Annuler',
      'confirm': 'Confirmer',
      'ok': 'OK',
      'back': 'Retour',
      'close': 'Fermer',
      'save': 'Enregistrer',
      'delete': 'Supprimer',
      'edit': 'Modifier',
      'completed': 'Terminé',
      'report_problem': 'Signaler un problème',
    },
    'es': {
      'settings': 'Configuración',
      'appearance': 'Apariencia',
      'dark_mode': 'Modo oscuro',
      'dark_mode_active': 'Activo',
      'dark_mode_inactive': 'Inactivo',
      'notifications': 'Notificaciones',
      'push_notifications': 'Notificaciones push',
      'push_notifications_subtitle': 'Recibir notificaciones en la app',
      'push_notifications_detail': 'Notificaciones inmediatas',
      'privacy_security': 'Privacidad y Seguridad',
      'privacy': 'Privacidad',
      'privacy_subtitle': 'Gestiona tu privacidad',
      'terms_conditions': 'Términos y Condiciones',
      'terms_conditions_subtitle': 'Lee los términos de uso',
      'privacy_policy': 'Política de Privacidad',
      'privacy_policy_subtitle': 'Cómo utilizamos tus datos',
      'support': 'Soporte',
      'help_support': 'Ayuda y Soporte',
      'help_support_subtitle': 'Preguntas frecuentes y asistencia',
      'info': 'Información',
      'info_subtitle': 'Versión 1.0.0',
      'general': 'General',
      'language': 'Idioma',
      'language_subtitle': 'Español',
      'apply': 'Aplicar',
      'select_language': 'Seleccionar idioma',
      'select_language_subtitle': 'Elige tu idioma preferido para la app.',
      'language_change_info': 'El cambio de idioma requerirá reiniciar la app para aplicarse completamente.',
      'home': 'Inicio',
      'map': 'Mapa',
      'search': 'Buscar',
      'available_cells': 'Disponibilidad',
      'cells': 'celdas',
      'open': 'Abrir',
      'profile': 'Perfil',
      'usage_history': 'Historial de uso',
      'active_cells': 'Celdas activas',
      'borrowed_items': 'Artículos prestados',
      'active_deposits': 'Depósitos activos',
      'pickup_orders': 'Pedidos para recoger',
      'return': 'Devolver',
      'unlock_cell': 'Desbloquear celda',
      'reports': 'Informes',
      'new_report': 'Nuevo informe',
      'donate': 'Donar un artículo',
      'new_donation': 'Nueva donación',
      'help': 'Ayuda y Soporte',
      'logout': 'Cerrar sesión',
      'report_issue': 'Reportar un problema',
      'category': 'Categoría',
      'description': 'Descripción',
      'photo': 'Foto',
      'send_report': 'Enviar informe',
      'report_sent': 'Informe enviado',
      'report_sent_message': 'Tu informe ha sido enviado con éxito.',
      'donation_history': 'Historial de donaciones',
      'donation_status_pending': 'Pendiente de verificación',
      'donation_status_confirmed': 'Confirmada',
      'donation_status_delivered': 'Entregada',
      'donation_status_rejected': 'Rechazada',
      'cancel': 'Cancelar',
      'confirm': 'Confirmar',
      'ok': 'OK',
      'back': 'Atrás',
      'close': 'Cerrar',
      'save': 'Guardar',
      'delete': 'Eliminar',
      'edit': 'Editar',
      'completed': 'Completado',
      'report_problem': 'Reportar un problema',
    },
  };

  String translate(String key) {
    final localeCode = _currentLocale.languageCode;
    return _translations[localeCode]?[key] ?? _translations['it']?[key] ?? key;
  }

  void setLocale(Locale locale) {
    if (_currentLocale != locale) {
      _currentLocale = locale;
      notifyListeners();
    }
  }

  String getLanguageName(String code) {
    switch (code) {
      case 'it':
        return 'Italiano';
      case 'en':
        return 'English';
      case 'de':
        return 'Deutsch';
      case 'fr':
        return 'Français';
      case 'es':
        return 'Español';
      default:
        return code;
    }
  }
}

